### PR TITLE
bot: refresh blockhash more frequently when sending transactions

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

The bot attempts to use the same recent blockhash for all transactions when sending transactions.  If there are many transactions to send, the recent blockhash can expire before all transactions have been sent, leading to many failures

#### Changes

Occasionally query the cluster to check the current blockhash's TTL and refresh it when half-expired

### CODE REVIEW

**Comment by meyerbro** [comment]
Hey, it looks like the bot ran in testnet, unfortunately after the end of epoch 212.

But it looks like it didn't action on mainnet, it just updated the wiki but didn't apply the changes/stakes on the nodes or posted on discord.

**Comment by t-nelson** [comment]
MB will run this evening

**Comment by meyerbro** [comment]
Just to understand it @t-nelson , the wiki pages:
https://github.com/solana-labs/stake-o-matic/wiki/Mainnet
https://github.com/solana-labs/stake-o-matic/wiki/Testnet
and each validator wiki page

Are independently updated?

I mean, if they get updated, it doesn't mean that the bot has already run for them?

Because yesterday I saw that it updated the wiki for both mainnet and testnet but didn't apply anything on mainnet but just testnet.

**Comment by t-nelson** [comment]
Yes, there's a flag on whether to dry-run or submit transactions which was set to dry-run for MB last night.  They should get run tonight.

I'll discuss with @mvines as to whether that flag should also affect wiki updates.  Seems like it should IMO

**Comment by meyerbro** [comment]
Thanks for your work on this @t-nelson !

**Comment by mvines** [comment]
Hey I saw a new commit get pushed here, but please lmk if that means this PR ready for review

**Pull request closed without merging**
